# Generated by Django 3.0.5 on 2020-11-01 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testmodel',
            options={'verbose_name': 'Test model', 'verbose_name_plural': 'Test models'},
        ),
    ]
